"""Saved login sessions: playwright cookies → Netscape cookies.txt on disk.

Storage layer only (pure, no network, no camoufox import). A saved session is
just a cookies.txt file that auth.load_cookies already parses — the fetcher
layer never changes. Files live under ~/.mdnow/sessions/<host>.txt with
owner-only permissions (dir 0o700, file 0o600).

Cookie VALUES are secrets: they exist only in the session file body — never
in exception messages, log lines, or return values.
"""
from __future__ import annotations

import os
from pathlib import Path

SESSION_DIR = Path.home() / ".mdnow" / "sessions"

_HEADER = "# Netscape HTTP Cookie File\n# Generated by mdnow --login. Do not edit.\n\n"


def _host_key(host: str) -> str:
    """Normalize a host for use as a session filename: lowercase, port stripped."""
    return host.split(":")[0].lower()


def _unsafe(c: dict) -> bool:
    """A tab/newline in any field would break the 7-field line format — a
    crafted value could even inject a second cookie line for another domain.
    Real browsers reject control chars in cookies, so skipping is lossless."""
    text_fields = (c.get("domain", ""), c.get("path", "/"), c["name"], c["value"])
    return not c.get("domain") or any(
        ch in field for field in text_fields for ch in "\t\r\n"
    )


def to_netscape(cookies: list[dict]) -> str:
    """Serialize playwright context cookies to Netscape cookies.txt text.

    Field order: domain, include_subdomains, path, secure, expiry, name, value.
    httpOnly cookies get the '#HttpOnly_' domain prefix (curl convention,
    stripped back out by auth._from_netscape). Cookies that can't be
    represented safely (control chars / no domain) are skipped.
    """
    lines = [_HEADER.rstrip("\n")]
    for c in cookies:
        if _unsafe(c):
            continue
        domain = c["domain"]
        prefix = "#HttpOnly_" if c.get("httpOnly") else ""
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = str(max(int(c.get("expires") or 0), 0))  # session cookie -1/None → 0
        fields = (
            f"{prefix}{domain}", include_subdomains, c.get("path", "/"),
            secure, expiry, c["name"], c["value"],
        )
        lines.append("\t".join(fields))
    return "\n".join(lines) + "\n"


def save_session(host: str, cookies: list[dict]) -> Path:
    """Write cookies for *host* to the session store; return the file path."""
    SESSION_DIR.mkdir(parents=True, exist_ok=True)
    SESSION_DIR.chmod(0o700)
    path = SESSION_DIR / f"{_host_key(host)}.txt"
    # owner-only from the first byte: never a umask-perm window on secrets
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(to_netscape(cookies))
    path.chmod(0o600)  # O_CREAT mode doesn't tighten a pre-existing file
    return path


def lookup_session(host: str) -> Path | None:
    """Return the saved session file for *host* (exact match), or None."""
    path = SESSION_DIR / f"{_host_key(host)}.txt"
    return path if path.is_file() else None
